### ISSUE TITLE
大佬，启动服务报错

### ISSUE THREAD

**Issue by xieruan** [GeekQu/SSPanelSubcribe#1]
php easyswoole start出现
#0 /www/wwwroot/SSPanelSubcribe/vendor/easyswoole/easyswoole/src/Config.php(25): EasySwoole\Config\TableConfig->__construct()
#1 /www/wwwroot/SSPanelSubcribe/vendor/easyswoole/component/src/Singleton.php(19): EasySwoole\EasySwoole\Config->__construct()
#2 /www/wwwroot/SSPanelSubcribe/vendor/easyswoole/easyswoole/src/Core.php(294): EasySwoole\EasySwoole\Config::getInstance()
#3 /www/wwwroot/SSPanelSubcribe/vendor/easyswoole/easyswoole/src/Core.php(100): EasySwoole\EasySwoole\Core->loadEnv()
#4 /www/wwwroot/SSPanelSubcribe/vendor/easyswoole/easyswoole/src/Command/CommandRunner.php(49): EasySwoole\EasySwoole\Core->initialize()
#5 /www/wwwroot/SSPanelSubcribe/easyswoole(24): EasySwoole\EasySwoole\Command\CommandRunner->run(Array)
#6 {main}
  thrown in /www/wwwroot/SSPanelSubcribe/vendor/easyswoole/config/src/TableConfig.php on line 17

**Comment by Nonage** [comment]
检查数据库配置
